/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	obs: {
		enabled?: boolean;
		address?: string;
		port?: number;
		sources?: {
			feed1?: string;
			feed2?: string;
			feed3?: string;
			feed4?: string;
			[k: string]: unknown;
		};
		[k: string]: unknown;
	};
}
