/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CurrentPlayers {
	player1?: {
		name?: string;
		twitch?: string;
		[k: string]: unknown;
	};
	player2?: {
		name?: string;
		twitch?: string;
		[k: string]: unknown;
	};
	player3?: {
		name?: string;
		twitch?: string;
		[k: string]: unknown;
	};
	player4?: {
		name?: string;
		twitch?: string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
